const productCatalog = {
  magtein: {
    title: 'Magtein® Magnesium L-Threonate', kicker: 'Brain / Focus / 06', slug: 'magnesium-l-threonate', image: '../assets/magnesium-l-threonate-hero-v2.jpg', alt: 'ICON FORMULAS Magtein Magnesium L-Threonate bottle on limestone', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Magtein+Magnesium+L-Threonate',
    description: 'Clinically studied magnesium L-threonate designed to support brain health, memory, and cognitive function — in the patented Magtein® form developed specifically to deliver magnesium to the brain.*',
    stats: [['2,000 mg', 'Magtein®'], ['144 mg', 'elemental magnesium'], ['90', 'capsules']],
    what: 'Supports brain health, memory, learning, and cognitive function by providing magnesium as Magtein® Magnesium L-Threonate.*', take: 'Take 3 capsules daily, preferably in divided doses, or as directed by a healthcare professional.', difference: 'Unlike conventional magnesium supplements designed primarily for whole-body intake, Magtein® was developed specifically with brain magnesium in mind.',
    formTitle: 'The form matters when the goal is focus.', formCopy: 'Magtein® is a patented form of magnesium L-threonate developed specifically to increase magnesium levels in the brain. It has been investigated in human clinical research for memory, learning, executive function, and other measures of cognitive performance.* We use 2,000 mg per daily serving — the amount used in clinical research — rather than chasing the biggest elemental-magnesium number.', noteLabel: 'Branded form / Magtein®', noteTitle: 'Precision for the moments that ask more of you.', noteText: '2,000 mg Magtein® delivers 144 mg of elemental magnesium in a 3-capsule daily serving.',
    benefits: [['Brain health', 'Provides magnesium in the specialized Magtein® form developed with brain magnesium in mind.*'], ['Memory & learning', 'Supports neuronal and synaptic processes involved in healthy memory formation, learning, and recall.*'], ['Cognitive function', 'Clinically studied to support aspects of cognitive performance, including executive function and working memory.*'], ['Healthy aging', 'Supports normal cognitive function and brain health as part of healthy aging.*'], ['Nervous system', 'Provides essential magnesium involved in healthy nerve signaling and normal nervous-system function.*']], quality: [['Authentic Magtein®', 'Patented, clinically studied Magnesium L-Threonate.'], ['Clinically studied dose', '2,000 mg per daily serving.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Ingredient clarity', 'The label shows 144 mg elemental magnesium from Magtein®.']], facts: [['Serving size', '3 capsules'], ['Servings per container', '30'], ['Magnesium', '144 mg'], ['Source', '2,000 mg Magtein® Magnesium L-Threonate']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.'
  },
  iron: {
    title: 'Iron Bisglycinate 36 mg', kicker: 'Energy / Foundation / 02', slug: 'iron-bisglycinate', image: '../assets/iron-bisglycinate.jpg', alt: 'ICON FORMULAS Iron Bisglycinate bottle', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Iron+Bisglycinate+36mg',
    description: 'Highly bioavailable chelated iron to support healthy iron levels, red blood cell formation, oxygen transport, and energy metabolism — in a well-tolerated form that is gentle on the digestive system.*', stats: [['36 mg', 'elemental iron'], ['Ferrochel®', 'iron bisglycinate'], ['1', 'capsule daily']],
    what: 'Provides 36 mg elemental iron to support healthy iron status, red blood cell formation, oxygen transport, and normal energy metabolism.*', take: 'Take 1 capsule daily, preferably with food, or as directed by a healthcare professional.', difference: 'Ferrochel® Ferrous Bisglycinate Chelate balances a meaningful iron dose with a form selected for bioavailability and gastrointestinal tolerance.',
    formTitle: 'Iron, chosen for balance.', formCopy: 'Ferrochel® is a clinically studied chelated form in which iron is bound to the amino acid glycine. It has been investigated for bioavailability and tolerability and is designed to provide iron in a form that is gentle on the digestive system.* For an iron supplement, getting enough matters — but so does choosing a form people can comfortably take as part of a routine.', noteLabel: 'Branded form / Ferrochel®', noteTitle: 'A more considered way to supplement iron.', noteText: '36 mg of elemental iron in a simple one-capsule serving.',
    benefits: [['Healthy iron levels', 'Provides 36 mg elemental iron to help support and maintain healthy iron status.*'], ['Red blood cells', 'Iron is essential for normal hemoglobin and red blood cell production.*'], ['Oxygen transport', 'Hemoglobin relies on iron to transport oxygen from the lungs to tissues.*'], ['Energy metabolism', 'Iron plays an essential role in cellular energy production.*'], ['Digestive comfort', 'Ferrochel® is selected with gastrointestinal tolerance in mind.*']], quality: [['Ferrochel®', 'Clinically studied ferrous bisglycinate chelate.'], ['Meaningful dose', '36 mg elemental iron per capsule.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Simple routine', 'One capsule daily, preferably with food.']], facts: [['Serving size', '1 capsule'], ['Servings per container', '60'], ['Iron', '36 mg'], ['Source', 'Ferrochel® Ferrous Bisglycinate Chelate']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.', warning: 'Iron supplementation should be individualized. Follow your healthcare professional’s guidance.'
  },
  zinc: {
    title: 'Zinc Bisglycinate 25 mg', kicker: 'Foundation / Daily / 01', slug: 'zinc-bisglycinate', image: '../assets/zinc-bisglycinate.jpg', alt: 'ICON FORMULAS Zinc Bisglycinate bottle', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Zinc+Bisglycinate+25mg',
    description: 'Highly bioavailable zinc bisglycinate to support immune function, healthy skin, hair and nails, antioxidant defenses, and normal reproductive health — in a well-tolerated chelated form.*', stats: [['25 mg', 'elemental zinc'], ['Albion®', 'TRAACS® chelate'], ['1', 'capsule daily']],
    what: 'Provides 25 mg elemental zinc to support healthy immune function, antioxidant defenses, skin integrity, and normal reproductive health.*', take: 'Take 1 capsule daily, preferably with food, or as directed by a healthcare professional.', difference: 'Albion® TRAACS® Zinc Bisglycinate Chelate is selected for ingredient quality, consistency, bioavailability, and gastrointestinal tolerance.',
    formTitle: 'The source matters as much as the number.', formCopy: 'Zinc bisglycinate is a chelated form in which zinc is bound to molecules of glycine. Albion® TRAACS® technology gives the mineral a recognized source and a consistent chelated structure rather than leaving the form unspecified.* For us, choosing zinc means choosing the form and the source — not simply the milligrams on the front.', noteLabel: 'Branded form / Albion® TRAACS®', noteTitle: 'A clear source for an everyday mineral.', noteText: '25 mg elemental zinc from a recognized mineral amino acid chelate.',
    benefits: [['Immune function', 'Supports normal development and function of immune cells.*'], ['Skin, hair & nails', 'Supports normal cellular growth and repair.*'], ['Antioxidant defenses', 'Contributes to the body’s natural antioxidant defenses.*'], ['Reproductive health', 'Supports normal reproductive function and hormone metabolism.*'], ['Cellular function', 'Acts as a cofactor for enzymes involved in normal tissue maintenance.*']], quality: [['Albion® TRAACS®', 'Recognized mineral amino acid chelation technology.'], ['Meaningful dose', '25 mg elemental zinc per capsule.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Label clarity', 'The mineral source is named on the label.']], facts: [['Serving size', '1 capsule'], ['Servings per container', '120'], ['Zinc', '25 mg'], ['Source', 'Albion® Zinc Bisglycinate Chelate']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.'
  },
  k2: {
    title: 'Vitamin K2 MK-7 120 mcg', kicker: 'Bones / Balance / 03', slug: 'vitamin-k2-mk7', image: '../assets/vitamin-k2-mk7.jpg', alt: 'ICON FORMULAS Vitamin K2 MK-7 bottle', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Vitamin+K2+MK-7+120mcg',
    description: 'Clinically studied Vitamin K2 as MK-7 to support healthy calcium utilization, strong bones, and cardiovascular health.*', stats: [['120 mcg', 'vitamin K2'], ['MenaQ7®', 'MK-7 source'], ['1', 'capsule daily']],
    what: 'Vitamin K2 supports the body’s proper use of calcium by activating vitamin K-dependent proteins involved in calcium metabolism.*', take: 'Take 1 capsule daily, preferably with food, or as directed by a healthcare professional.', difference: 'MenaQ7® is a naturally fermented, clinically studied source of Vitamin K2 as MK-7 with documented purity and consistency.',
    formTitle: 'Calcium is only part of the story.', formCopy: 'Vitamin K2 activates proteins involved in calcium metabolism. Osteocalcin supports incorporation of calcium into bone, while Matrix Gla Protein (MGP) helps regulate calcium within the cardiovascular system.* We chose menaquinone-7 because it is a highly bioavailable, long-lasting form, then chose MenaQ7® for its documented quality and human research.', noteLabel: 'Branded form / MenaQ7®', noteTitle: 'A clearer way to think about K2.', noteText: 'MenaQ7® MK-7 connects a once-daily dose to the proteins involved in healthy calcium regulation.', mechanism: true,
    benefits: [['Calcium utilization', 'Supports vitamin K-dependent proteins that help regulate calcium.*'], ['Strong bones', 'Helps activate osteocalcin, a protein involved in healthy bone mineralization.*'], ['Cardiovascular health', 'Helps activate MGP, involved in healthy calcium regulation.*'], ['Long-lasting MK-7', 'Provides a highly bioavailable form with a longer presence in circulation.*'], ['One daily capsule', '120 mcg in a simple once-daily serving.']], quality: [['MenaQ7®', 'Naturally fermented, clinically studied MK-7.'], ['Documented source', 'Selected for purity and consistency.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Clear caution', 'Check with a healthcare professional if taking anticoagulants.']], facts: [['Serving size', '1 capsule'], ['Servings per container', '60'], ['Vitamin K2', '120 mcg'], ['Source', 'Menaquinone-7 from MenaQ7®']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.', warning: 'If you are taking anticoagulant medication, consult your healthcare professional before using a Vitamin K supplement.'
  },
  magnesium200: {
    title: 'Magnesium Bisglycinate Chelate 200 mg', kicker: 'Foundation / Recovery / 04', slug: 'magnesium-bisglycinate-200', image: '../assets/magnesium-bisglycinate-200.jpg', alt: 'ICON FORMULAS Magnesium Bisglycinate 200 mg bottle', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Magnesium+Bisglycinate+200mg',
    description: 'Everyday magnesium support with 200 mg elemental magnesium in a convenient two-capsule serving — formulated with Albion® TRAACS® Buffered Magnesium Bisglycinate Chelate.*', stats: [['200 mg', 'elemental magnesium'], ['2', 'capsules per serving'], ['60', 'servings']],
    what: 'Provides 200 mg elemental magnesium to support relaxation, healthy muscle and nerve function, restful sleep, and cellular energy production.*', take: 'Take 2 capsules daily, preferably with food, or as directed by a healthcare professional.', difference: 'Albion® TRAACS® Buffered Magnesium Bisglycinate Chelate combines magnesium bisglycinate chelate with magnesium oxide to provide a practical amount of elemental magnesium in two capsules.',
    formTitle: 'Everyday support, deliberately buffered.', formCopy: 'This formula uses Albion® TRAACS® Buffered Magnesium Bisglycinate Chelate — a proprietary approach that combines a bisglycinate-based chelate with magnesium oxide to provide a higher concentration of elemental magnesium. The result is 200 mg in two capsules, designed for consistent everyday supplementation.*', noteLabel: 'Branded form / Albion® TRAACS®', noteTitle: 'A practical daily magnesium routine.', noteText: '200 mg elemental magnesium from 1,167 mg buffered chelate per serving.',
    benefits: [['Relaxation', 'Promotes relaxation and supports restful sleep.*'], ['Muscle function', 'Supports normal muscle contraction and relaxation.*'], ['Nervous system', 'Supports healthy nerve function and nerve signaling.*'], ['Cellular energy', 'Supports cellular energy production and normal metabolism.*'], ['Bone & heart', 'Provides essential magnesium for bone and cardiovascular health.*']], quality: [['Buffered chelate', 'Albion® TRAACS® technology.'], ['Practical serving', '200 mg in two capsules.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Clear amount', 'The elemental amount is easy to find.']], facts: [['Serving size', '2 capsules'], ['Servings per container', '60'], ['Magnesium', '200 mg'], ['Source', '1,167 mg Albion® Magnesium Bisglycinate Chelate Buffered']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.'
  },
  magnesium225: {
    title: 'Magnesium Bisglycinate Chelate 225 mg', kicker: 'Foundation / Recovery / 05', slug: 'magnesium-bisglycinate-225', image: '../assets/magnesium-bisglycinate-225.jpg', alt: 'ICON FORMULAS Magnesium Bisglycinate 225 mg bottle', amazon: 'https://www.amazon.com/s?k=ICON+FORMULAS+Magnesium+Bisglycinate+225mg',
    description: 'Highly bioavailable magnesium bisglycinate to support relaxation, healthy muscle and nerve function, restful sleep, and cellular energy — in a fully reacted chelated form that is gentle on the digestive system.*', stats: [['225 mg', 'elemental magnesium'], ['TRAACS®', 'fully reacted chelate'], ['90', 'capsules']],
    what: 'Supports relaxation, restful sleep, healthy muscle and nerve function, and cellular energy production while providing magnesium in a highly bioavailable, well-tolerated chelated form.*', take: 'Take 3 capsules daily, preferably with food, or as directed by a healthcare professional.', difference: 'All 225 mg comes from Albion® TRAACS® Magnesium Bisglycinate Chelate — a fully reacted amino acid chelate. No magnesium oxide or other magnesium form is added to increase the elemental amount.',
    formTitle: 'A fully reacted chelate, kept true to form.', formCopy: 'Magnesium bisglycinate binds magnesium to two molecules of glycine. We use Albion® TRAACS® Magnesium Bisglycinate Chelate, a fully reacted mineral amino acid chelate whose structure is analytically verified. The formula stays true to that choice: all 225 mg comes from bisglycinate chelate.*', noteLabel: 'Branded form / Albion® TRAACS®', noteTitle: 'No shortcuts in the elemental amount.', noteText: '225 mg elemental magnesium from 2,363 mg fully reacted bisglycinate chelate.',
    benefits: [['Relaxation', 'Promotes relaxation and supports restful, restorative sleep.*'], ['Muscle function', 'Supports normal muscle contraction and relaxation.*'], ['Nervous system', 'Supports healthy nerve function and nerve signaling.*'], ['Cellular energy', 'Supports cellular energy production and normal metabolism.*'], ['Bone & heart', 'Provides essential magnesium for bone and cardiovascular health.*']], quality: [['Fully reacted chelate', 'Albion® TRAACS® structure, analytically verified.'], ['No added oxide', 'All 225 mg comes from bisglycinate chelate.'], ['Made in the USA', 'Manufactured in a cGMP- and NSF-certified facility.'], ['Clear amount', 'The elemental amount is easy to find.']], facts: [['Serving size', '3 capsules'], ['Servings per container', '30'], ['Magnesium', '225 mg'], ['Source', '2,363 mg Albion® Magnesium Bisglycinate Chelate']], ingredients: 'Microcrystalline Cellulose (Veg Grade), Magnesium Stearate, Silicon Dioxide, Vegetable Capsule.'
  }
};

const pageKey = document.body.dataset.productPage;
const product = productCatalog[pageKey];
if (product) {
  document.title = `${product.title} — Icon Formulas`;
  document.querySelector('meta[name="description"]').setAttribute('content', product.description.replace('*', ''));
  document.querySelector('#product-kicker').textContent = product.kicker;
  document.querySelector('#product-title').textContent = product.title;
  document.querySelector('#product-description').textContent = product.description;
  const image = document.querySelector('#product-image'); image.src = product.image; image.alt = product.alt;
  document.querySelector('#product-hero-index').textContent = `FORMULA / ${product.kicker.split('/').pop().trim()}`;
  document.querySelector('#product-amazon').href = product.amazon;
  document.querySelector('#product-stats').innerHTML = product.stats.map(([value,label]) => `<div><strong>${value}</strong><span>${label}</span></div>`).join('');
  document.querySelector('#product-what').textContent = product.what;
  document.querySelector('#product-take').textContent = product.take;
  document.querySelector('#product-difference').textContent = product.difference;
  document.querySelector('#form-title').textContent = product.formTitle;
  document.querySelector('#form-copy').textContent = product.formCopy;
  document.querySelector('#form-note-label').textContent = product.noteLabel;
  document.querySelector('#form-note-title').textContent = product.noteTitle;
  document.querySelector('#form-note-text').textContent = product.noteText;
  document.querySelector('#benefit-grid').innerHTML = product.benefits.map((item, index) => `<article class="benefit-card" style="--accent:var(--${['blue','lavender','amber','pink','violet'][index]})"><span>0${index + 1}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('');
  document.querySelector('#quality-list').innerHTML = product.quality.map(([title,text]) => `<li><strong>${title}</strong>${text}</li>`).join('');
  document.querySelector('#facts-table').innerHTML = product.facts.map(([label,value]) => `<tr><td>${label}</td><td>${value}</td></tr>`).join('');
  document.querySelector('#ingredients').textContent = product.ingredients;
  document.querySelector('#product-warning').textContent = product.warning || '';
  document.querySelector('#mechanism-card')?.classList.toggle('is-visible', Boolean(product.mechanism));

  // Put the buying argument in the same order a careful shopper evaluates it:
  // benefit first, then the chosen form, then routine details and label proof.
  const heroSection = document.querySelector('.product-hero');
  const benefitSection = document.querySelector('#benefit-grid')?.closest('.product-page__section');
  const formSection = document.querySelector('.form-story')?.closest('.product-page__section');
  const essentialsSection = document.querySelector('#product-what')?.closest('.product-page__section');
  if (heroSection && benefitSection && formSection && essentialsSection) {
    heroSection.insertAdjacentElement('afterend', benefitSection);
    benefitSection.insertAdjacentElement('afterend', formSection);
    formSection.insertAdjacentElement('afterend', essentialsSection);
  }

  const routineSection = document.createElement('section');
  routineSection.className = 'product-lifestyle section-shell';
  routineSection.innerHTML = '<div class="product-lifestyle__image"><img src="../assets/routine-lifestyle.png" alt="Woman enjoying a quiet evening wellness routine with water and a book" loading="lazy"></div><div class="product-lifestyle__copy"><div class="section-kicker">Built for the day you actually have</div><h2>A routine<br>you can <em>keep.</em></h2><p>One clear purpose. One considered form. No unnecessary noise.</p></div>';
  formSection?.insertAdjacentElement('afterend', routineSection);

  const benefitsKicker = benefitSection?.querySelector('.section-kicker');
  const benefitsIntro = benefitSection?.querySelector('.product-page__section-head > p');
  if (benefitsKicker) benefitsKicker.textContent = 'Start with the benefit';
  if (benefitsIntro) benefitsIntro.textContent = 'A clear purpose comes first. Then we show the form, dose, and source behind that promise.';
  const formKicker = formSection?.querySelector('.section-kicker');
  if (formKicker) formKicker.textContent = 'Science & sourcing';

  const qualityIntro = document.querySelector('.quality-panel--dark > p');
  if (qualityIntro) qualityIntro.textContent = 'A premium formula should make its reasoning visible: the named source, the ingredient form, the active amount, and the manufacturing standard.';
}
